name: neon_ui_design
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_svg: ^1.1.6
  glassmorphism: ^3.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/actor1.png
    - assets/images/actress1.png
    - assets/images/actress2.png
    - assets/images/actress3.png
    - assets/images/image 84.png
    - assets/images/image 90.png
    - assets/images/image 91.png
    - assets/images/image 92.png
    - assets/images/image 93.png
    - assets/images/image 94.png
    - assets/images/mainScreenImage.png
    - assets/images/movieBgImage.png
    - assets/svgImages/magnifyingglass.svg
    - assets/svgImages/microphone.svg
    - assets/svgImages/plus.svg
    - assets/svgImages/home.svg
    - assets/svgImages/play.svg
    - assets/svgImages/folder.svg
    - assets/svgImages/download.svg
    - assets/svgImages/back.svg
    - assets/svgImages/menu.svg
    - assets/masks/tryMask.png
    - assets/masks/imageMask.png
    - assets/masks/lastMask.png
    - assets/masks/castMask.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
